//! Hkx XML file Root Element
use super::generated::class_params::ClassParams;
use serde::{Deserialize, Serialize};
use std::borrow::Cow;

/// Hkx file Root
#[derive(Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename = "hkpackfile")]
pub struct Hkx<'a> {
    /// In the case of SkyrimSE, `8`.
    #[serde(rename = "@classversion")]
    pub class_version: u64,

    /// In the case of SkyrimSE, `"hk_2010.2.0-r1"`.
    #[serde(rename = "@contentsversion")]
    pub content_version: Cow<'a, str>,
    #[serde(rename = "@toplevelobject")]

    /// e.g. `#0056`
    pub top_level_object: Cow<'a, str>,

    /// data sections
    #[serde(rename = "hksection")]
    #[serde(bound(deserialize = "HkSection<'a>: Deserialize<'de>"))]
    pub hk_section: HkSection<'a>,
}

/// section name & class vector
#[derive(Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(rename = "hksection")]
pub struct HkSection<'a> {
    /// e.g. `"__data__"`
    #[serde(rename = "@name", borrow, skip_deserializing)]
    #[serde(default = "default_section_root")]
    pub name: Cow<'a, str>,

    /// C++ class vector for the `hkobject` tag
    #[serde(bound(deserialize = "Vec<Class<'a>>: Deserialize<'de>"))]
    #[serde(rename = "hkobject", borrow)]
    pub classes: Vec<Class<'a>>,
}

/// Return `"__data__"`
fn default_section_root() -> Cow<'static, str> {
    "__data__".into()
}

/// In XML, it is enclosed in a `hkobject` tag
/// and the `class` attribute contains the C++ class name
///
///# Note
/// This `Class` [`serde::Serialize`]/[`serde::Deserialize`] is automatically generated by generated::class_params.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Class<'a> {
    /// e.g. `#0106`
    ///
    /// In XML, these names are referenced (in C++ implementations) by vectors that store pointers to a structure and a class.
    pub name: Cow<'a, str>,

    /// Name of each C++ class.
    ///
    /// e.g. `"hkbBehaviorGraphStringData"`
    pub class: Cow<'a, str>,

    /// Signature of each class.
    ///
    /// e.g. `0xc713064e`
    ///
    /// #Note
    /// In some cases, the signature of the parent class is inherited, in which case it is duplicated.
    /// Because of the possibility of duplication, use the class name instead of the signature for the serializer/deserializer.
    pub signature: Cow<'a, str>,

    /// The `"hkparam"` tag (C++ fields) vector
    pub hkparams: ClassParams<'a>,
}
