//! This file is generated by `crate/src/generators/generated/cpp_type_parser.rs`
//! Please do not edit this file.

#[allow(unused)]
#[rustfmt::skip]
/// Mapping tuple between C++ Havok alias type-inclusive types and Rust types.
pub const HK_TYPES: [(&str, &str); 522] = [
    (
        "char*",
        "Cow<'a, str>",
    ),
    (
        "enum AbsoluteTimeCounter",
        "AbsoluteTimeCounter",
    ),
    (
        "enum AlignMode",
        "AlignMode",
    ),
    (
        "enum AnimationType",
        "AnimationType",
    ),
    (
        "enum ArrayType",
        "ArrayType",
    ),
    (
        "enum AtomType",
        "AtomType",
    ),
    (
        "enum AttachmentType",
        "AttachmentType",
    ),
    (
        "enum BindingType",
        "BindingType",
    ),
    (
        "enum BlendCurve",
        "BlendCurve",
    ),
    (
        "enum BlendHint",
        "BlendHint",
    ),
    (
        "enum BlendModeFunction",
        "BlendModeFunction",
    ),
    (
        "enum BroadPhaseBorderBehaviour",
        "BroadPhaseBorderBehaviour",
    ),
    (
        "enum BuildType",
        "BuildType",
    ),
    (
        "enum BvTreeType",
        "BvTreeType",
    ),
    (
        "enum CallbackType",
        "CallbackType",
    ),
    (
        "enum CharacterControlCommand",
        "CharacterControlCommand",
    ),
    (
        "enum CollectionType",
        "CollectionType",
    ),
    (
        "enum ComponentType",
        "ComponentType",
    ),
    (
        "enum ComponentUsage",
        "ComponentUsage",
    ),
    (
        "enum ConstraintPriority",
        "ConstraintPriority",
    ),
    (
        "enum ContactPointGeneration",
        "ContactPointGeneration",
    ),
    (
        "enum DataType",
        "DataType",
    ),
    (
        "enum DataUsage",
        "DataUsage",
    ),
    (
        "enum EffectType",
        "EffectType",
    ),
    (
        "enum EndMode",
        "EndMode",
    ),
    (
        "enum Event",
        "Event",
    ),
    (
        "enum EventMode",
        "EventMode",
    ),
    (
        "enum EventRangeMode",
        "EventRangeMode",
    ),
    (
        "enum ExpressionEventMode",
        "ExpressionEventMode",
    ),
    (
        "enum ExtendedColors",
        "ExtendedColors",
    ),
    (
        "enum FilterMode",
        "FilterMode",
    ),
    (
        "enum Format",
        "Format",
    ),
    (
        "enum GizmoType",
        "GizmoType",
    ),
    (
        "enum HandleChangeMode",
        "HandleChangeMode",
    ),
    (
        "enum HeightFieldType",
        "HeightFieldType",
    ),
    (
        "enum HideInModeler",
        "HideInModeler",
    ),
    (
        "enum Hint",
        "Hint",
    ),
    (
        "enum IndexStridingType",
        "IndexStridingType",
    ),
    (
        "enum IndexType",
        "IndexType",
    ),
    (
        "enum InitialVelocityCoordinates",
        "InitialVelocityCoordinates",
    ),
    (
        "enum KeyboardKey",
        "KeyboardKey",
    ),
    (
        "enum LastProcessingStep",
        "LastProcessingStep",
    ),
    (
        "enum LightType",
        "LightType",
    ),
    (
        "enum LinearVelocityMode",
        "LinearVelocityMode",
    ),
    (
        "enum Link",
        "Link",
    ),
    (
        "enum MappingType",
        "MappingType",
    ),
    (
        "enum MaterialIndexStridingType",
        "MaterialIndexStridingType",
    ),
    (
        "enum MaterialType",
        "MaterialType",
    ),
    (
        "enum MeasurementMode",
        "MeasurementMode",
    ),
    (
        "enum MeshSectionIndexType",
        "MeshSectionIndexType",
    ),
    (
        "enum MeshShapeIndexStridingType",
        "MeshShapeIndexStridingType",
    ),
    (
        "enum MeshShapeMaterialIndexStridingType",
        "MeshShapeMaterialIndexStridingType",
    ),
    (
        "enum Mode",
        "Mode",
    ),
    (
        "enum ModelerType",
        "ModelerType",
    ),
    (
        "enum MotionMode",
        "MotionMode",
    ),
    (
        "enum MotionType",
        "MotionType",
    ),
    (
        "enum MotorType",
        "MotorType",
    ),
    (
        "enum NodeType",
        "NodeType",
    ),
    (
        "enum OnDestructionRemapInfo",
        "OnDestructionRemapInfo",
    ),
    (
        "enum Operation",
        "Operation",
    ),
    (
        "enum Operator",
        "Operator",
    ),
    (
        "enum OrientationConstraintType",
        "OrientationConstraintType",
    ),
    (
        "enum PhantomType",
        "PhantomType",
    ),
    (
        "enum PlaybackMode",
        "PlaybackMode",
    ),
    (
        "enum PrimitiveType",
        "PrimitiveType",
    ),
    (
        "enum ResponseType",
        "ResponseType",
    ),
    (
        "enum Role",
        "Role",
    ),
    (
        "enum RotationAxisCoordinates",
        "RotationAxisCoordinates",
    ),
    (
        "enum RotationQuantization",
        "RotationQuantization",
    ),
    (
        "enum ScalarQuantization",
        "ScalarQuantization",
    ),
    (
        "enum SelfTransitionMode",
        "SelfTransitionMode",
    ),
    (
        "enum Semantics",
        "Semantics",
    ),
    (
        "enum SensingMode",
        "SensingMode",
    ),
    (
        "enum SerializedAgentType",
        "SerializedAgentType",
    ),
    (
        "enum SetAngleMethod",
        "SetAngleMethod",
    ),
    (
        "enum ShaderType",
        "ShaderType",
    ),
    (
        "enum SimulationControlCommand",
        "SimulationControlCommand",
    ),
    (
        "enum SimulationState",
        "SimulationState",
    ),
    (
        "enum SimulationType",
        "SimulationType",
    ),
    (
        "enum SolvingMethod",
        "SolvingMethod",
    ),
    (
        "enum Stage",
        "Stage",
    ),
    (
        "enum StartStateMode",
        "StartStateMode",
    ),
    (
        "enum StateMachineSelfTransitionMode",
        "StateMachineSelfTransitionMode",
    ),
    (
        "enum SubpartType",
        "SubpartType",
    ),
    (
        "enum SystemType",
        "SystemType",
    ),
    (
        "enum TextureType",
        "TextureType",
    ),
    (
        "enum TextureUsageType",
        "TextureUsageType",
    ),
    (
        "enum ToGeneratorState",
        "ToGeneratorState",
    ),
    (
        "enum TokenType",
        "TokenType",
    ),
    (
        "enum ToolNodeType",
        "ToolNodeType",
    ),
    (
        "enum TreeUpdateType",
        "TreeUpdateType",
    ),
    (
        "enum Type",
        "Type",
    ),
    (
        "enum VariableMode",
        "VariableMode",
    ),
    (
        "enum VariableType",
        "VariableType",
    ),
    (
        "enum VertexFloatDimensions",
        "VertexFloatDimensions",
    ),
    (
        "enum WeldingType",
        "WeldingType",
    ),
    (
        "enum WorldFromModelMode",
        "WorldFromModelMode",
    ),
    (
        "enum hkpFilterType",
        "HkpFilterType",
    ),
    (
        "enum unknown",
        "Unknown",
    ),
    (
        "flags FlagBits",
        "FlagBits",
    ),
    (
        "flags FlagValues",
        "FlagValues",
    ),
    (
        "flags Flags",
        "Flags",
    ),
    (
        "flags HintFlags",
        "HintFlags",
    ),
    (
        "flags RoleFlags",
        "RoleFlags",
    ),
    (
        "flags TransitionFlags",
        "TransitionFlags",
    ),
    (
        "flags unknown",
        "Unknown",
    ),
    (
        "hkArray&lt;BSBoneSwitchGeneratorBoneData*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkBool&gt;",
        "HkArrayRef<Primitive<bool>>",
    ),
    (
        "hkArray&lt;hkChar&gt;",
        "HkArrayRef<Primitive<char>>",
    ),
    (
        "hkArray&lt;hkInt16&gt;",
        "HkArrayRef<Primitive<i16>>",
    ),
    (
        "hkArray&lt;hkInt32&gt;",
        "HkArrayRef<Primitive<i32>>",
    ),
    (
        "hkArray&lt;hkInt8&gt;",
        "HkArrayRef<Primitive<i8>>",
    ),
    (
        "hkArray&lt;hkLocalFrame*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkMatrix4&gt;",
        "HkArrayVector<Matrix4<f32>>",
    ),
    (
        "hkArray&lt;hkMemoryResourceContainer*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkMemoryResourceHandle*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkMeshTexture*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkMeshVertexBuffer*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkQsTransform&gt;",
        "HkArrayVector<QsTransform<f32>>",
    ),
    (
        "hkArray&lt;hkQuaternion&gt;",
        "HkArrayVector<Quaternion<f32>>",
    ),
    (
        "hkArray&lt;hkReal&gt;",
        "HkArrayRef<Primitive<f32>>",
    ),
    (
        "hkArray&lt;hkReferencedObject*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkStringPtr&gt;",
        "HkArrayStringPtr<'a>",
    ),
    (
        "hkArray&lt;hkTransform&gt;",
        "HkArrayVector<Transform<f32>>",
    ),
    (
        "hkArray&lt;hkUint16&gt;",
        "HkArrayRef<Primitive<u16>>",
    ),
    (
        "hkArray&lt;hkUint32&gt;",
        "HkArrayRef<Primitive<u32>>",
    ),
    (
        "hkArray&lt;hkUint64&gt;",
        "HkArrayRef<Primitive<u64>>",
    ),
    (
        "hkArray&lt;hkUint8&gt;",
        "HkArrayRef<Primitive<u8>>",
    ),
    (
        "hkArray&lt;hkVector4&gt;",
        "HkArrayVector<Vector4<f32>>",
    ),
    (
        "hkArray&lt;hkaAnimation*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkaAnimationBinding*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkaBoneAttachment*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkaFootstepAnalysisInfo*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkaMeshBinding*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkaSkeleton*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkaSkeletonMapper*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkbAuxiliaryNodeInfo*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkbBehaviorGraph*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkbBlenderGeneratorChild*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkbBoolVariableSequencedData*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkbCharacter*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkbEventPayload*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkbEventSequencedData*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkbGenerator*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkbIntVariableSequencedData*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkbModifier*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkbNodeInternalStateInfo*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkbRealVariableSequencedData*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkbStateListener*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkbStateMachineStateInfo*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpAction*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpAgent1nSector*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpCollisionFilter*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpConstraintChainInstance*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpConstraintInstance*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpConstraintMotor*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpConvexShape*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpDisplayBindingDataPhysicsSystem*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpDisplayBindingDataRigidBody*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpEntity*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpPhantom*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpPhysicsSystem*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpRigidBody*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpSerializedAgentNnEntry*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpSerializedDisplayMarker*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpSerializedSubTrack1nInfo*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpStorageExtendedMeshShapeMeshSubpartStorage*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpStorageExtendedMeshShapeShapeSubpartStorage*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpStorageMeshShapeSubpartStorage*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpTyremarksWheel*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkpVehicleInstance*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkxCamera*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkxIndexBuffer*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkxLight*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkxMaterial*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkxMaterialShader*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkxMesh*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkxMeshSection*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkxMeshUserChannelInfo*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkxNode*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkxNodeSelectionSet*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkxSkinBinding*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkxTextureFile*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;hkxTextureInplace*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkArray&lt;struct BSIStateManagerModifierBSiStateData&gt;",
        "HkArrayClass<BsiStateManagerModifierBSiStateData>",
    ),
    (
        "hkArray&lt;struct BSLookAtModifierBoneData&gt;",
        "HkArrayClass<BsLookAtModifierBoneData>",
    ),
    (
        "hkArray&lt;struct hkContactPoint&gt;",
        "HkArrayClass<HkContactPoint>",
    ),
    (
        "hkArray&lt;struct hkGeometryTriangle&gt;",
        "HkArrayClass<HkGeometryTriangle>",
    ),
    (
        "hkArray&lt;struct hkMemoryResourceHandleExternalLink&gt;",
        "HkArrayClass<HkMemoryResourceHandleExternalLink>",
    ),
    (
        "hkArray&lt;struct hkMeshBoneIndexMapping&gt;",
        "HkArrayClass<HkMeshBoneIndexMapping>",
    ),
    (
        "hkArray&lt;struct hkMeshSectionCinfo&gt;",
        "HkArrayClass<HkMeshSectionCinfo>",
    ),
    (
        "hkArray&lt;struct hkMonitorStreamColorTableColorPair&gt;",
        "HkArrayClass<HkMonitorStreamColorTableColorPair>",
    ),
    (
        "hkArray&lt;struct hkMonitorStreamStringMapStringMap&gt;",
        "HkArrayClass<HkMonitorStreamStringMapStringMap>",
    ),
    (
        "hkArray&lt;struct hkMultipleVertexBufferElementInfo&gt;",
        "HkArrayClass<HkMultipleVertexBufferElementInfo>",
    ),
    (
        "hkArray&lt;struct hkMultipleVertexBufferLockedElement&gt;",
        "HkArrayClass<HkMultipleVertexBufferLockedElement>",
    ),
    (
        "hkArray&lt;struct hkMultipleVertexBufferVertexBufferInfo&gt;",
        "HkArrayClass<HkMultipleVertexBufferVertexBufferInfo>",
    ),
    (
        "hkArray&lt;struct hkRootLevelContainerNamedVariant&gt;",
        "HkArrayClass<HkRootLevelContainerNamedVariant>",
    ),
    (
        "hkArray&lt;struct hkTrackerSerializableScanSnapshotAllocation&gt;",
        "HkArrayClass<HkTrackerSerializableScanSnapshotAllocation>",
    ),
    (
        "hkArray&lt;struct hkTrackerSerializableScanSnapshotBlock&gt;",
        "HkArrayClass<HkTrackerSerializableScanSnapshotBlock>",
    ),
    (
        "hkArray&lt;struct hkaAnnotationTrack&gt;",
        "HkArrayClass<HkaAnnotationTrack>",
    ),
    (
        "hkArray&lt;struct hkaAnnotationTrackAnnotation&gt;",
        "HkArrayClass<HkaAnnotationTrackAnnotation>",
    ),
    (
        "hkArray&lt;struct hkaBone&gt;",
        "HkArrayClass<HkaBone>",
    ),
    (
        "hkArray&lt;struct hkaMeshBindingMapping&gt;",
        "HkArrayClass<HkaMeshBindingMapping>",
    ),
    (
        "hkArray&lt;struct hkaSkeletonLocalFrameOnBone&gt;",
        "HkArrayClass<HkaSkeletonLocalFrameOnBone>",
    ),
    (
        "hkArray&lt;struct hkaSkeletonMapperDataChainMapping&gt;",
        "HkArrayClass<HkaSkeletonMapperDataChainMapping>",
    ),
    (
        "hkArray&lt;struct hkaSkeletonMapperDataSimpleMapping&gt;",
        "HkArrayClass<HkaSkeletonMapperDataSimpleMapping>",
    ),
    (
        "hkArray&lt;struct hkbAttributeModifierAssignment&gt;",
        "HkArrayClass<HkbAttributeModifierAssignment>",
    ),
    (
        "hkArray&lt;struct hkbBehaviorInfoIdToNamePair&gt;",
        "HkArrayClass<HkbBehaviorInfoIdToNamePair>",
    ),
    (
        "hkArray&lt;struct hkbBlenderGeneratorChildInternalState&gt;",
        "HkArrayClass<HkbBlenderGeneratorChildInternalState>",
    ),
    (
        "hkArray&lt;struct hkbBoolVariableSequencedDataSample&gt;",
        "HkArrayClass<HkbBoolVariableSequencedDataSample>",
    ),
    (
        "hkArray&lt;struct hkbClipGeneratorEcho&gt;",
        "HkArrayClass<HkbClipGeneratorEcho>",
    ),
    (
        "hkArray&lt;struct hkbClipTrigger&gt;",
        "HkArrayClass<HkbClipTrigger>",
    ),
    (
        "hkArray&lt;struct hkbCompiledExpressionSetToken&gt;",
        "HkArrayClass<HkbCompiledExpressionSetToken>",
    ),
    (
        "hkArray&lt;struct hkbEvaluateExpressionModifierInternalExpressionData&gt;",
        "HkArrayClass<HkbEvaluateExpressionModifierInternalExpressionData>",
    ),
    (
        "hkArray&lt;struct hkbEventInfo&gt;",
        "HkArrayClass<HkbEventInfo>",
    ),
    (
        "hkArray&lt;struct hkbEventProperty&gt;",
        "HkArrayClass<HkbEventProperty>",
    ),
    (
        "hkArray&lt;struct hkbEventRangeData&gt;",
        "HkArrayClass<HkbEventRangeData>",
    ),
    (
        "hkArray&lt;struct hkbEventSequencedDataSequencedEvent&gt;",
        "HkArrayClass<HkbEventSequencedDataSequencedEvent>",
    ),
    (
        "hkArray&lt;struct hkbExpressionData&gt;",
        "HkArrayClass<HkbExpressionData>",
    ),
    (
        "hkArray&lt;struct hkbFootIkControlsModifierLeg&gt;",
        "HkArrayClass<HkbFootIkControlsModifierLeg>",
    ),
    (
        "hkArray&lt;struct hkbFootIkDriverInfoLeg&gt;",
        "HkArrayClass<HkbFootIkDriverInfoLeg>",
    ),
    (
        "hkArray&lt;struct hkbFootIkModifierInternalLegData&gt;",
        "HkArrayClass<HkbFootIkModifierInternalLegData>",
    ),
    (
        "hkArray&lt;struct hkbFootIkModifierLeg&gt;",
        "HkArrayClass<HkbFootIkModifierLeg>",
    ),
    (
        "hkArray&lt;struct hkbHandIkControlsModifierHand&gt;",
        "HkArrayClass<HkbHandIkControlsModifierHand>",
    ),
    (
        "hkArray&lt;struct hkbHandIkDriverInfoHand&gt;",
        "HkArrayClass<HkbHandIkDriverInfoHand>",
    ),
    (
        "hkArray&lt;struct hkbHandIkModifierHand&gt;",
        "HkArrayClass<HkbHandIkModifierHand>",
    ),
    (
        "hkArray&lt;struct hkbIntVariableSequencedDataSample&gt;",
        "HkArrayClass<HkbIntVariableSequencedDataSample>",
    ),
    (
        "hkArray&lt;struct hkbKeyframeBonesModifierKeyframeInfo&gt;",
        "HkArrayClass<HkbKeyframeBonesModifierKeyframeInfo>",
    ),
    (
        "hkArray&lt;struct hkbRealVariableSequencedDataSample&gt;",
        "HkArrayClass<HkbRealVariableSequencedDataSample>",
    ),
    (
        "hkArray&lt;struct hkbSenseHandleModifierRange&gt;",
        "HkArrayClass<HkbSenseHandleModifierRange>",
    ),
    (
        "hkArray&lt;struct hkbStateMachineActiveTransitionInfo&gt;",
        "HkArrayClass<HkbStateMachineActiveTransitionInfo>",
    ),
    (
        "hkArray&lt;struct hkbStateMachineDelayedTransitionInfo&gt;",
        "HkArrayClass<HkbStateMachineDelayedTransitionInfo>",
    ),
    (
        "hkArray&lt;struct hkbStateMachineTransitionInfo&gt;",
        "HkArrayClass<HkbStateMachineTransitionInfo>",
    ),
    (
        "hkArray&lt;struct hkbVariableBindingSetBinding&gt;",
        "HkArrayClass<HkbVariableBindingSetBinding>",
    ),
    (
        "hkArray&lt;struct hkbVariableInfo&gt;",
        "HkArrayClass<HkbVariableInfo>",
    ),
    (
        "hkArray&lt;struct hkbVariableValue&gt;",
        "HkArrayClass<HkbVariableValue>",
    ),
    (
        "hkArray&lt;struct hkpBallSocketChainDataConstraintInfo&gt;",
        "HkArrayClass<HkpBallSocketChainDataConstraintInfo>",
    ),
    (
        "hkArray&lt;struct hkpCompressedMeshShapeBigTriangle&gt;",
        "HkArrayClass<HkpCompressedMeshShapeBigTriangle>",
    ),
    (
        "hkArray&lt;struct hkpCompressedMeshShapeChunk&gt;",
        "HkArrayClass<HkpCompressedMeshShapeChunk>",
    ),
    (
        "hkArray&lt;struct hkpCompressedMeshShapeConvexPiece&gt;",
        "HkArrayClass<HkpCompressedMeshShapeConvexPiece>",
    ),
    (
        "hkArray&lt;struct hkpConvexVerticesShapeFourVectors&gt;",
        "HkArrayClass<HkpConvexVerticesShapeFourVectors>",
    ),
    (
        "hkArray&lt;struct hkpExtendedMeshShapeShapesSubpart&gt;",
        "HkArrayClass<HkpExtendedMeshShapeShapesSubpart>",
    ),
    (
        "hkArray&lt;struct hkpExtendedMeshShapeTrianglesSubpart&gt;",
        "HkArrayClass<HkpExtendedMeshShapeTrianglesSubpart>",
    ),
    (
        "hkArray&lt;struct hkpListShapeChildInfo&gt;",
        "HkArrayClass<HkpListShapeChildInfo>",
    ),
    (
        "hkArray&lt;struct hkpMeshShapeSubpart&gt;",
        "HkArrayClass<HkpMeshShapeSubpart>",
    ),
    (
        "hkArray&lt;struct hkpMultiRayShapeRay&gt;",
        "HkArrayClass<HkpMultiRayShapeRay>",
    ),
    (
        "hkArray&lt;struct hkpNamedMeshMaterial&gt;",
        "HkArrayClass<HkpNamedMeshMaterial>",
    ),
    (
        "hkArray&lt;struct hkpPoweredChainDataConstraintInfo&gt;",
        "HkArrayClass<HkpPoweredChainDataConstraintInfo>",
    ),
    (
        "hkArray&lt;struct hkpPoweredChainMapperLinkInfo&gt;",
        "HkArrayClass<HkpPoweredChainMapperLinkInfo>",
    ),
    (
        "hkArray&lt;struct hkpPoweredChainMapperTarget&gt;",
        "HkArrayClass<HkpPoweredChainMapperTarget>",
    ),
    (
        "hkArray&lt;struct hkpProperty&gt;",
        "HkArrayClass<HkpProperty>",
    ),
    (
        "hkArray&lt;struct hkpSerializedDisplayRbTransformsDisplayTransformPair&gt;",
        "HkArrayClass<HkpSerializedDisplayRbTransformsDisplayTransformPair>",
    ),
    (
        "hkArray&lt;struct hkpSimpleMeshShapeTriangle&gt;",
        "HkArrayClass<HkpSimpleMeshShapeTriangle>",
    ),
    (
        "hkArray&lt;struct hkpSimpleShapePhantomCollisionDetail&gt;",
        "HkArrayClass<HkpSimpleShapePhantomCollisionDetail>",
    ),
    (
        "hkArray&lt;struct hkpStiffSpringChainDataConstraintInfo&gt;",
        "HkArrayClass<HkpStiffSpringChainDataConstraintInfo>",
    ),
    (
        "hkArray&lt;struct hkpStorageExtendedMeshShapeMaterial&gt;",
        "HkArrayClass<HkpStorageExtendedMeshShapeMaterial>",
    ),
    (
        "hkArray&lt;struct hkpTriggerVolumeEventInfo&gt;",
        "HkArrayClass<HkpTriggerVolumeEventInfo>",
    ),
    (
        "hkArray&lt;struct hkpTyremarkPoint&gt;",
        "HkArrayClass<HkpTyremarkPoint>",
    ),
    (
        "hkArray&lt;struct hkpVehicleDataWheelComponentParams&gt;",
        "HkArrayClass<HkpVehicleDataWheelComponentParams>",
    ),
    (
        "hkArray&lt;struct hkpVehicleDefaultBrakeWheelBrakingProperties&gt;",
        "HkArrayClass<HkpVehicleDefaultBrakeWheelBrakingProperties>",
    ),
    (
        "hkArray&lt;struct hkpVehicleDefaultSuspensionWheelSpringSuspensionParameters&gt;",
        "HkArrayClass<HkpVehicleDefaultSuspensionWheelSpringSuspensionParameters>",
    ),
    (
        "hkArray&lt;struct hkpVehicleInstanceWheelInfo&gt;",
        "HkArrayClass<HkpVehicleInstanceWheelInfo>",
    ),
    (
        "hkArray&lt;struct hkpVehicleLinearCastWheelCollideWheelState&gt;",
        "HkArrayClass<HkpVehicleLinearCastWheelCollideWheelState>",
    ),
    (
        "hkArray&lt;struct hkpVehicleSuspensionSuspensionWheelParameters&gt;",
        "HkArrayClass<HkpVehicleSuspensionSuspensionWheelParameters>",
    ),
    (
        "hkArray&lt;struct hkxAttribute&gt;",
        "HkArrayClass<HkxAttribute>",
    ),
    (
        "hkArray&lt;struct hkxAttributeGroup&gt;",
        "HkArrayClass<HkxAttributeGroup>",
    ),
    (
        "hkArray&lt;struct hkxEnumItem&gt;",
        "HkArrayClass<HkxEnumItem>",
    ),
    (
        "hkArray&lt;struct hkxEnvironmentVariable&gt;",
        "HkArrayClass<HkxEnvironmentVariable>",
    ),
    (
        "hkArray&lt;struct hkxMaterialProperty&gt;",
        "HkArrayClass<HkxMaterialProperty>",
    ),
    (
        "hkArray&lt;struct hkxMaterialTextureStage&gt;",
        "HkArrayClass<HkxMaterialTextureStage>",
    ),
    (
        "hkArray&lt;struct hkxNodeAnnotationData&gt;",
        "HkArrayClass<HkxNodeAnnotationData>",
    ),
    (
        "hkArray&lt;struct hkxVertexDescriptionElementDecl&gt;",
        "HkArrayClass<HkxVertexDescriptionElementDecl>",
    ),
    (
        "hkArray&lt;void&gt;",
        "HkArrayRef<()>",
    ),
    (
        "hkArray&lt;void*&gt;",
        "HkArrayRef<Cow<'a, str>>",
    ),
    (
        "hkBool",
        "Primitive<bool>",
    ),
    (
        "hkBool[1]",
        "[Primitive<bool>; 1]",
    ),
    (
        "hkBool[3]",
        "[Primitive<bool>; 3]",
    ),
    (
        "hkChar",
        "Primitive<char>",
    ),
    (
        "hkChar[16]",
        "[Primitive<char>; 16]",
    ),
    (
        "hkChar[19]",
        "[Primitive<char>; 19]",
    ),
    (
        "hkChar[32]",
        "[Primitive<char>; 32]",
    ),
    (
        "hkChar[4]",
        "[Primitive<char>; 4]",
    ),
    (
        "hkHalf",
        "Primitive<f32>",
    ),
    (
        "hkHalf[8]",
        "[Primitive<f32>; 8]",
    ),
    (
        "hkInt16",
        "Primitive<i16>",
    ),
    (
        "hkInt16[4]",
        "[Primitive<i16>; 4]",
    ),
    (
        "hkInt32",
        "Primitive<i32>",
    ),
    (
        "hkInt32[1]",
        "[Primitive<i32>; 1]",
    ),
    (
        "hkInt32[2]",
        "[Primitive<i32>; 2]",
    ),
    (
        "hkInt32[32]",
        "[Primitive<i32>; 32]",
    ),
    (
        "hkInt32[3]",
        "[Primitive<i32>; 3]",
    ),
    (
        "hkInt8",
        "Primitive<i8>",
    ),
    (
        "hkMatrix3",
        "Matrix3<f32>",
    ),
    (
        "hkMatrix4",
        "Matrix4<f32>",
    ),
    (
        "hkQsTransform",
        "QsTransform<f32>",
    ),
    (
        "hkQuaternion",
        "Quaternion<f32>",
    ),
    (
        "hkReal",
        "Primitive<f32>",
    ),
    (
        "hkReal[16]",
        "[Primitive<f32>; 16]",
    ),
    (
        "hkRotation",
        "Rotation<f32>",
    ),
    (
        "hkSimpleArray&lt;struct hkClassEnum&gt;",
        "HkArrayClass<HkClassEnum>",
    ),
    (
        "hkSimpleArray&lt;struct hkClassEnumItem&gt;",
        "HkArrayClass<HkClassEnumItem>",
    ),
    (
        "hkSimpleArray&lt;struct hkClassMember&gt;",
        "HkArrayClass<HkClassMember>",
    ),
    (
        "hkSimpleArray&lt;struct hkCustomAttributesAttribute&gt;",
        "HkArrayClass<HkCustomAttributesAttribute>",
    ),
    (
        "hkSimpleArray&lt;void&gt;",
        "HkArrayRef<()>",
    ),
    (
        "hkStringPtr",
        "HkStringPtr",
    ),
    (
        "hkTransform",
        "Transform<f32>",
    ),
    (
        "hkTransform[2]",
        "[Transform<f32>; 2]",
    ),
    (
        "hkUint16",
        "Primitive<u16>",
    ),
    (
        "hkUint16[2]",
        "[Primitive<u16>; 2]",
    ),
    (
        "hkUint16[6]",
        "[Primitive<u16>; 6]",
    ),
    (
        "hkUint32",
        "Primitive<u32>",
    ),
    (
        "hkUint32[2]",
        "[Primitive<u32>; 2]",
    ),
    (
        "hkUint32[32]",
        "[Primitive<u32>; 32]",
    ),
    (
        "hkUint32[3]",
        "[Primitive<u32>; 3]",
    ),
    (
        "hkUint32[5]",
        "[Primitive<u32>; 5]",
    ),
    (
        "hkUint32[8]",
        "[Primitive<u32>; 8]",
    ),
    (
        "hkUint64",
        "Primitive<u64>",
    ),
    (
        "hkUint8",
        "Primitive<u8>",
    ),
    (
        "hkUint8[12]",
        "[Primitive<u8>; 12]",
    ),
    (
        "hkUint8[160]",
        "[Primitive<u8>; 160]",
    ),
    (
        "hkUint8[3]",
        "[Primitive<u8>; 3]",
    ),
    (
        "hkUint8[496]",
        "[Primitive<u8>; 496]",
    ),
    (
        "hkUint8[4]",
        "[Primitive<u8>; 4]",
    ),
    (
        "hkUint8[8]",
        "[Primitive<u8>; 8]",
    ),
    (
        "hkUlong",
        "Primitive<usize>",
    ),
    (
        "hkVariant",
        "Primitive<u64>",
    ),
    (
        "hkVector4",
        "Vector4<f32>",
    ),
    (
        "hkVector4[2]",
        "[Vector4<f32>; 2]",
    ),
    (
        "hkVector4[4]",
        "[Vector4<f32>; 4]",
    ),
    (
        "hkVector4[8]",
        "[Vector4<f32>; 8]",
    ),
    (
        "struct BSIStateManagerModifierBSIStateManagerStateListener",
        "BsiStateManagerModifierBsiStateManagerStateListener",
    ),
    (
        "struct hkAabb",
        "HkAabb",
    ),
    (
        "struct hkClass*",
        "Cow<'a, str>",
    ),
    (
        "struct hkClassEnum*",
        "Cow<'a, str>",
    ),
    (
        "struct hkContactPoint",
        "HkContactPoint",
    ),
    (
        "struct hkCustomAttributes*",
        "Cow<'a, str>",
    ),
    (
        "struct hkIndexedTransformSet*",
        "Cow<'a, str>",
    ),
    (
        "struct hkLocalFrame*",
        "Cow<'a, str>",
    ),
    (
        "struct hkLocalFrameGroup*",
        "Cow<'a, str>",
    ),
    (
        "struct hkMemoryMeshVertexBuffer*",
        "Cow<'a, str>",
    ),
    (
        "struct hkMemoryResourceContainer*",
        "Cow<'a, str>",
    ),
    (
        "struct hkMeshMaterial*",
        "Cow<'a, str>",
    ),
    (
        "struct hkMeshShape*",
        "Cow<'a, str>",
    ),
    (
        "struct hkMeshVertexBuffer*",
        "Cow<'a, str>",
    ),
    (
        "struct hkMotionState",
        "HkMotionState",
    ),
    (
        "struct hkMultiThreadCheck",
        "HkMultiThreadCheck",
    ),
    (
        "struct hkReferencedObject*",
        "Cow<'a, str>",
    ),
    (
        "struct hkSweptTransform",
        "HkSweptTransform",
    ),
    (
        "struct hkVertexFormat",
        "HkVertexFormat",
    ),
    (
        "struct hkVertexFormatElement[32]",
        "[HkVertexFormatElement; 32]",
    ),
    (
        "struct hkWorldMemoryAvailableWatchDog*",
        "Cow<'a, str>",
    ),
    (
        "struct hkaAnimatedReferenceFrame*",
        "Cow<'a, str>",
    ),
    (
        "struct hkaAnimation*",
        "Cow<'a, str>",
    ),
    (
        "struct hkaDeltaCompressedAnimationQuantizationFormat",
        "HkaDeltaCompressedAnimationQuantizationFormat",
    ),
    (
        "struct hkaKeyFrameHierarchyUtilityControlData",
        "HkaKeyFrameHierarchyUtilityControlData",
    ),
    (
        "struct hkaSkeleton*",
        "Cow<'a, str>",
    ),
    (
        "struct hkaSkeletonMapper*",
        "Cow<'a, str>",
    ),
    (
        "struct hkaSkeletonMapperData",
        "HkaSkeletonMapperData",
    ),
    (
        "struct hkaWaveletCompressedAnimationQuantizationFormat",
        "HkaWaveletCompressedAnimationQuantizationFormat",
    ),
    (
        "struct hkbAttachmentSetup*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbBehaviorGraph*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbBehaviorGraphData*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbBehaviorGraphInternalState*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbBehaviorGraphStringData*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbBoneIndexArray*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbBoneWeightArray*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbCharacter*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbCharacterControllerControlData",
        "HkbCharacterControllerControlData",
    ),
    (
        "struct hkbCharacterData*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbCharacterDataCharacterControllerInfo",
        "HkbCharacterDataCharacterControllerInfo",
    ),
    (
        "struct hkbCharacterSetup*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbCharacterStringData*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbClipTriggerArray*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbCondition*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbEvent",
        "HkbEvent",
    ),
    (
        "struct hkbEventPayload*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbEventProperty",
        "HkbEventProperty",
    ),
    (
        "struct hkbEventRangeDataArray*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbExpressionDataArray*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbFootIkControlData",
        "HkbFootIkControlData",
    ),
    (
        "struct hkbFootIkDriverInfo*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbFootIkGains",
        "HkbFootIkGains",
    ),
    (
        "struct hkbGenerator*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbGeneratorOutputListener*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbGeneratorSyncInfo",
        "HkbGeneratorSyncInfo",
    ),
    (
        "struct hkbGeneratorSyncInfoSyncPoint[8]",
        "[HkbGeneratorSyncInfoSyncPoint; 8]",
    ),
    (
        "struct hkbHandIkControlData",
        "HkbHandIkControlData",
    ),
    (
        "struct hkbHandIkDriverInfo*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbHandle",
        "HkbHandle",
    ),
    (
        "struct hkbHandle*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbMirroredSkeletonInfo*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbModifier*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbNodeInternalStateInfo*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbPoweredRagdollControlData",
        "HkbPoweredRagdollControlData",
    ),
    (
        "struct hkbProjectData*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbProjectStringData*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbProxyModifierProxyInfo",
        "HkbProxyModifierProxyInfo",
    ),
    (
        "struct hkbRigidBodyRagdollControlData",
        "HkbRigidBodyRagdollControlData",
    ),
    (
        "struct hkbRoleAttribute",
        "HkbRoleAttribute",
    ),
    (
        "struct hkbSequenceStringData*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbStateChooser*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbStateMachineEventPropertyArray*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbStateMachineProspectiveTransitionInfo",
        "HkbStateMachineProspectiveTransitionInfo",
    ),
    (
        "struct hkbStateMachineTimeInterval",
        "HkbStateMachineTimeInterval",
    ),
    (
        "struct hkbStateMachineTransitionInfoArray*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbStateMachineTransitionInfoReference",
        "HkbStateMachineTransitionInfoReference",
    ),
    (
        "struct hkbTransitionEffect*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbVariableBindingSet*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbVariableValue",
        "HkbVariableValue",
    ),
    (
        "struct hkbVariableValueSet*",
        "Cow<'a, str>",
    ),
    (
        "struct hkbWorldFromModelModeData",
        "HkbWorldFromModelModeData",
    ),
    (
        "struct hkp2dAngConstraintAtom",
        "Hkp2DAngConstraintAtom",
    ),
    (
        "struct hkpAabbPhantom*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpAngConstraintAtom",
        "HkpAngConstraintAtom",
    ),
    (
        "struct hkpAngFrictionConstraintAtom",
        "HkpAngFrictionConstraintAtom",
    ),
    (
        "struct hkpAngLimitConstraintAtom",
        "HkpAngLimitConstraintAtom",
    ),
    (
        "struct hkpAngMotorConstraintAtom",
        "HkpAngMotorConstraintAtom",
    ),
    (
        "struct hkpBallAndSocketConstraintDataAtoms",
        "HkpBallAndSocketConstraintDataAtoms",
    ),
    (
        "struct hkpBallSocketConstraintAtom",
        "HkpBallSocketConstraintAtom",
    ),
    (
        "struct hkpBridgeAtoms",
        "HkpBridgeAtoms",
    ),
    (
        "struct hkpBridgeConstraintAtom",
        "HkpBridgeConstraintAtom",
    ),
    (
        "struct hkpCdBody*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpCharacterControllerCinfo*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpCogWheelConstraintAtom",
        "HkpCogWheelConstraintAtom",
    ),
    (
        "struct hkpCogWheelConstraintDataAtoms",
        "HkpCogWheelConstraintDataAtoms",
    ),
    (
        "struct hkpCollidable*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpCollidableBoundingVolumeData",
        "HkpCollidableBoundingVolumeData",
    ),
    (
        "struct hkpCollisionFilter*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpConeLimitConstraintAtom",
        "HkpConeLimitConstraintAtom",
    ),
    (
        "struct hkpConstraintAtom*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpConstraintChainInstance*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpConstraintChainInstanceAction*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpConstraintData*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpConstraintInstance*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpConstraintInstanceSmallArraySerializeOverrideType",
        "HkpConstraintInstanceSmallArraySerializeOverrideType",
    ),
    (
        "struct hkpConstraintMotor*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpConvexListFilter*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpConvexPieceStreamData*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpConvexVerticesConnectivity*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpEntity*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpEntityExtendedListeners*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpEntitySmallArraySerializeOverrideType",
        "HkpEntitySmallArraySerializeOverrideType",
    ),
    (
        "struct hkpEntitySpuCollisionCallback",
        "HkpEntitySpuCollisionCallback",
    ),
    (
        "struct hkpExtendedMeshShapeTrianglesSubpart",
        "HkpExtendedMeshShapeTrianglesSubpart",
    ),
    (
        "struct hkpGenericConstraintDataScheme",
        "HkpGenericConstraintDataScheme",
    ),
    (
        "struct hkpGenericConstraintDataSchemeConstraintInfo",
        "HkpGenericConstraintDataSchemeConstraintInfo",
    ),
    (
        "struct hkpHingeConstraintDataAtoms",
        "HkpHingeConstraintDataAtoms",
    ),
    (
        "struct hkpHingeLimitsDataAtoms",
        "HkpHingeLimitsDataAtoms",
    ),
    (
        "struct hkpLimitedHingeConstraintDataAtoms",
        "HkpLimitedHingeConstraintDataAtoms",
    ),
    (
        "struct hkpLinConstraintAtom",
        "HkpLinConstraintAtom",
    ),
    (
        "struct hkpLinFrictionConstraintAtom",
        "HkpLinFrictionConstraintAtom",
    ),
    (
        "struct hkpLinLimitConstraintAtom",
        "HkpLinLimitConstraintAtom",
    ),
    (
        "struct hkpLinMotorConstraintAtom",
        "HkpLinMotorConstraintAtom",
    ),
    (
        "struct hkpLinSoftConstraintAtom",
        "HkpLinSoftConstraintAtom",
    ),
    (
        "struct hkpLinkedCollidable",
        "HkpLinkedCollidable",
    ),
    (
        "struct hkpMaterial",
        "HkpMaterial",
    ),
    (
        "struct hkpMaxSizeMotion",
        "HkpMaxSizeMotion",
    ),
    (
        "struct hkpMaxSizeMotion*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpModifierConstraintAtom*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpMoppCode*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpMoppCodeCodeInfo",
        "HkpMoppCodeCodeInfo",
    ),
    (
        "struct hkpPairCollisionFilterMapPairFilterKeyOverrideType",
        "HkpPairCollisionFilterMapPairFilterKeyOverrideType",
    ),
    (
        "struct hkpParametricCurve*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpPhysicsSystem*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpPointToPlaneConstraintDataAtoms",
        "HkpPointToPlaneConstraintDataAtoms",
    ),
    (
        "struct hkpPoweredChainData*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpPrismaticConstraintDataAtoms",
        "HkpPrismaticConstraintDataAtoms",
    ),
    (
        "struct hkpPropertyValue",
        "HkpPropertyValue",
    ),
    (
        "struct hkpPulleyConstraintAtom",
        "HkpPulleyConstraintAtom",
    ),
    (
        "struct hkpPulleyConstraintDataAtoms",
        "HkpPulleyConstraintDataAtoms",
    ),
    (
        "struct hkpRackAndPinionConstraintAtom",
        "HkpRackAndPinionConstraintAtom",
    ),
    (
        "struct hkpRackAndPinionConstraintDataAtoms",
        "HkpRackAndPinionConstraintDataAtoms",
    ),
    (
        "struct hkpRagdollConstraintDataAtoms",
        "HkpRagdollConstraintDataAtoms",
    ),
    (
        "struct hkpRagdollLimitsDataAtoms",
        "HkpRagdollLimitsDataAtoms",
    ),
    (
        "struct hkpRagdollMotorConstraintAtom",
        "HkpRagdollMotorConstraintAtom",
    ),
    (
        "struct hkpRejectChassisListener",
        "HkpRejectChassisListener",
    ),
    (
        "struct hkpRigidBody*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpRotationalConstraintDataAtoms",
        "HkpRotationalConstraintDataAtoms",
    ),
    (
        "struct hkpSampledHeightFieldShape*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpSerializedTrack1nInfo",
        "HkpSerializedTrack1NInfo",
    ),
    (
        "struct hkpSetLocalRotationsConstraintAtom",
        "HkpSetLocalRotationsConstraintAtom",
    ),
    (
        "struct hkpSetLocalTransformsConstraintAtom",
        "HkpSetLocalTransformsConstraintAtom",
    ),
    (
        "struct hkpSetLocalTranslationsConstraintAtom",
        "HkpSetLocalTranslationsConstraintAtom",
    ),
    (
        "struct hkpSetupStabilizationAtom",
        "HkpSetupStabilizationAtom",
    ),
    (
        "struct hkpShape*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpShapeCollection*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpShapePhantom*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpSimpleContactConstraintAtom",
        "HkpSimpleContactConstraintAtom",
    ),
    (
        "struct hkpSimpleContactConstraintDataInfo",
        "HkpSimpleContactConstraintDataInfo",
    ),
    (
        "struct hkpSimulation*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpSingleShapeContainer",
        "HkpSingleShapeContainer",
    ),
    (
        "struct hkpStiffSpringConstraintAtom",
        "HkpStiffSpringConstraintAtom",
    ),
    (
        "struct hkpStiffSpringConstraintDataAtoms",
        "HkpStiffSpringConstraintDataAtoms",
    ),
    (
        "struct hkpTwistLimitConstraintAtom",
        "HkpTwistLimitConstraintAtom",
    ),
    (
        "struct hkpTypedBroadPhaseHandle",
        "HkpTypedBroadPhaseHandle",
    ),
    (
        "struct hkpTyremarksInfo*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpVehicleAerodynamics*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpVehicleBrake*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpVehicleData*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpVehicleDriverInput*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpVehicleDriverInputStatus*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpVehicleEngine*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpVehicleFrictionDescription",
        "HkpVehicleFrictionDescription",
    ),
    (
        "struct hkpVehicleFrictionDescriptionAxisDescription[2]",
        "[HkpVehicleFrictionDescriptionAxisDescription; 2]",
    ),
    (
        "struct hkpVehicleFrictionStatus",
        "HkpVehicleFrictionStatus",
    ),
    (
        "struct hkpVehicleFrictionStatusAxisStatus[2]",
        "[HkpVehicleFrictionStatusAxisStatus; 2]",
    ),
    (
        "struct hkpVehicleSteering*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpVehicleSuspension*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpVehicleTransmission*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpVehicleVelocityDamper*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpVehicleWheelCollide*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpWheelConstraintDataAtoms",
        "HkpWheelConstraintDataAtoms",
    ),
    (
        "struct hkpWorld*",
        "Cow<'a, str>",
    ),
    (
        "struct hkpWorldCinfo*",
        "Cow<'a, str>",
    ),
    (
        "struct hkxEnum*",
        "Cow<'a, str>",
    ),
    (
        "struct hkxMaterial*",
        "Cow<'a, str>",
    ),
    (
        "struct hkxMesh*",
        "Cow<'a, str>",
    ),
    (
        "struct hkxNode*",
        "Cow<'a, str>",
    ),
    (
        "struct hkxVertexBuffer*",
        "Cow<'a, str>",
    ),
    (
        "struct hkxVertexBufferVertexData",
        "HkxVertexBufferVertexData",
    ),
    (
        "struct hkxVertexDescription",
        "HkxVertexDescription",
    ),
    (
        "void*",
        "Cow<'a, str>",
    ),
];
